"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import "./simphony-admin.css";
import "./redwood-status.css";
import "./admin-navigation.css";

type Config=Record<"apiBaseUrl"|"oidcBaseUrl"|"clientId"|"username"|"password"|"orgShortName"|"locRef"|"rvcRef"|"employeeRef"|"orderTypeRef"|"orderChannelRef"|"tenderId"|"enabledTenderIds"|"tenderDisplayMode"|"menuId"|"menuItemId"|"quantity",string>;
type Action="test"|"menuSummary"|"menu"|"trainingCheck"|"activateMenu"|"tenders";
type Status="pending"|"testing"|"connected"|"error";
type ApiLog={time:string;action:string;status:number;ok:boolean;elapsed:number;message:string};
type Tender={tenderId:number;name:string;type:string};
const initial:Config={apiBaseUrl:"",oidcBaseUrl:"",clientId:"",username:"",password:"",orgShortName:"",locRef:"",rvcRef:"",employeeRef:"",orderTypeRef:"",orderChannelRef:"",tenderId:"",enabledTenderIds:"",tenderDisplayMode:"configured",menuId:"",menuItemId:"",quantity:"1"};
const CONFIG_KEY="omniorder.adminConfig", CONFIG_TTL=60*60*1000;
function loadConfig(){if(typeof window==="undefined")return initial;try{const saved=JSON.parse(sessionStorage.getItem(CONFIG_KEY)||"{}");return saved.expiresAt>Date.now()?saved.config as Config:initial;}catch{return initial;}}

export default function SimphonyAdmin(){
 const [config,setConfig]=useState<Config>(loadConfig),[status,setStatus]=useState<Status>("pending"),[message,setMessage]=useState("Aún no se ha validado la conexión."),[result,setResult]=useState<unknown>(null),[busy,setBusy]=useState<Action|null>(null),[lastValidated,setLastValidated]=useState<string>(),[elapsed,setElapsed]=useState<number>(),[catalogStatus,setCatalogStatus]=useState("No sincronizado"),[tenders,setTenders]=useState<Tender[]>([]),[tendersOpen,setTendersOpen]=useState(false);
 const [apiLog,setApiLog]=useState<ApiLog[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(sessionStorage.getItem("omniorder.orderLog")||"[]");}catch{return[];}});
 useEffect(()=>{const persist=()=>sessionStorage.setItem(CONFIG_KEY,JSON.stringify({config,expiresAt:Date.now()+CONFIG_TTL}));persist();["click","keydown","pointerdown"].forEach(event=>window.addEventListener(event,persist));return()=>["click","keydown","pointerdown"].forEach(event=>window.removeEventListener(event,persist));},[config]);
 useEffect(()=>{try{sessionStorage.setItem("omniorder.orderLog",JSON.stringify(apiLog));}catch{}},[apiLog]);
 const update=(key:keyof Config,value:string)=>setConfig(current=>({...current,[key]:key==="apiBaseUrl"||key==="oidcBaseUrl"?extractUrl(value):value}));
 const enabledIds=config.enabledTenderIds.split(",").filter(Boolean), locked=status!=="connected"||busy!==null;
 const toggleTender=(id:number)=>setConfig(current=>{const values=current.enabledTenderIds.split(",").filter(Boolean), value=String(id),next=values.includes(value)?values.filter(item=>item!==value):[...values,value];return {...current,enabledTenderIds:next.join(","),tenderId:next.includes(current.tenderId)?current.tenderId:(next[0]||"")};});
 async function run(action:Action){const started=performance.now();setBusy(action);setResult(null);if(action==="test"){setStatus("testing");setMessage("Autenticando y validando el Revenue Center...");}else setMessage("Ejecutando operación con Simphony...");try{const response=await fetch("/api/simphony",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,config})}),data=await response.json(),milliseconds=Math.round(performance.now()-started);setElapsed(milliseconds);setResult(data);setMessage(data.message||"Operación completada.");setApiLog(current=>[{time:new Date().toLocaleTimeString(),action,status:Number(data.status||response.status),ok:Boolean(data.ok),elapsed:milliseconds,message:String(data.message||"Sin mensaje")},...current].slice(0,12));if(action==="test"){if(data.ok){setStatus("connected");setLastValidated(new Date().toLocaleTimeString());}else setStatus("error");}if(action==="tenders"&&data.ok){const available=(data.tenders||[]) as Tender[];setTenders(available);setConfig(current=>{const existing=current.enabledTenderIds.split(",").filter(Boolean),defaults=available.filter(isCashOrCard).map(tender=>String(tender.tenderId)),ids=existing.length?existing:defaults;return {...current,enabledTenderIds:ids.join(","),tenderId:current.tenderId||ids[0]||""};});}if(action==="activateMenu"&&data.ok&&data.sessionId){sessionStorage.setItem("omniorder.simphonySession",data.sessionId);setCatalogStatus("Catálogo activo");}if(action!=="test"&&!data.ok)setCatalogStatus("Sincronización con error");}catch{const milliseconds=Math.round(performance.now()-started);setMessage("No fue posible comunicarse con el servidor local del lab.");setApiLog(current=>[{time:new Date().toLocaleTimeString(),action,status:0,ok:false,elapsed:milliseconds,message:"Sin respuesta del servidor local"},...current].slice(0,12));if(action==="test")setStatus("error");}finally{setBusy(null);}}
 const submit=(event:FormEvent)=>{event.preventDefault();void run("test");};
 return <main className="admin-shell"><header className="admin-header"><Link href="/" className="back">← Volver a Orden</Link><div><span className="admin-kicker">PARAMETRIZACIÓN LOCAL</span><h1>Admin de Simphony STS Gen 2</h1></div><span className="local-only">Solo sesión actual</span></header>
 <nav className="admin-section-nav"><a href="/">Orden</a><a href="#parametros">Parámetros</a><a href="#pagos">Pagos</a><a href="#sincronizar">Sincronizar</a><a href="#prueba">Prueba</a><a href="#logs">Logs</a></nav>
 <section className="connection-banner"><div className={`connection-icon ${status}`}>{status==="connected"?"✓":status==="error"?"!":"○"}</div><div><span className="admin-kicker">ESTADO DE CONEXIÓN</span><h2>{status==="connected"?"Conexión validada con Simphony":status==="testing"?"Validando conexión...":status==="error"?"Conexión no validada":"Pendiente de validación"}</h2><p>{message}</p></div><dl><div><dt>Última validación</dt><dd>{lastValidated||"Sin ejecutar"}</dd></div><div><dt>Tiempo de respuesta</dt><dd>{elapsed!==undefined?`${elapsed} ms`:"—"}</dd></div><div><dt>Catálogo</dt><dd>{catalogStatus}</dd></div></dl></section>
 <section className="admin-intro"><b>Las credenciales no se guardan ni se suben a Git.</b><span>Se conservan solo en la memoria local durante una hora de actividad.</span></section>
 <form onSubmit={submit} className="admin-grid"><section id="parametros" className="admin-card"><Title n="1" title="Conexión OIDC" text="Copia los valores exactos desde EMC."/><Field label="STS Gen2 Services URL" value={config.apiBaseUrl} onChange={v=>update("apiBaseUrl",v)} placeholder="https://mtu6-sts.oraclecloud.com/api/v1" required/><Field label="OpenID Provider URL" value={config.oidcBaseUrl} onChange={v=>update("oidcBaseUrl",v)} placeholder="https://mtu6-ohra.idm.oracleindustry.com/oidc-provider/" required/><Field label="Client ID" value={config.clientId} onChange={v=>update("clientId",v)} required/><Field label="Usuario API" value={config.username} onChange={v=>update("username",v)} required/><Field label="Contraseña API" type="password" value={config.password} onChange={v=>update("password",v)} required/></section>
 <section className="admin-card"><Title n="2" title="Contexto del lab" text="Destino operativo y menú expuesto al e-commerce."/><Field label="orgShortName" value={config.orgShortName} onChange={v=>update("orgShortName",v.toLowerCase())} required/><Field label="locRef" value={config.locRef} onChange={v=>update("locRef",v.toLowerCase())} required/><Field label="rvcRef" type="number" value={config.rvcRef} onChange={v=>update("rvcRef",v)} required/><Field label="menuId" value={config.menuId} onChange={v=>update("menuId",v)} placeholder="ID del menú" required/><Field label="checkEmployeeRef" type="number" value={config.employeeRef} onChange={v=>update("employeeRef",v)} required/><Field label="orderTypeRef" type="number" value={config.orderTypeRef} onChange={v=>update("orderTypeRef",v)} required/><Field label="orderChannelRef" type="number" value={config.orderChannelRef} onChange={v=>update("orderChannelRef",v)}/><button disabled={busy!==null} className="test-button" type="submit">{busy==="test"?"Validando...":"Probar autenticación y RVC"}</button></section>
 <section id="pagos" className="admin-card wide"><Title n="3" title="Formas de pago" text="Consulta el RVC y habilita solo los tenders que verá el cliente."/><button type="button" className="test-button" onClick={()=>void run("tenders")} disabled={status!=="connected"||busy!==null}>{busy==="tenders"?"Consultando...":"Consultar tenders del RVC"}</button>{tenders.length>0&&<details className="tender-accordion" open={tendersOpen} onToggle={event=>setTendersOpen((event.target as HTMLDetailsElement).open)}><summary><span><b>{tenders.length} tenders encontrados</b><small>{enabledIds.length} habilitado(s) para el e-commerce</small></span><em>{tendersOpen?"Ocultar":"Configurar"}</em></summary><div className="tender-config"><p>Por defecto se habilitan efectivo y tarjeta. El tender técnico serviceTotal se conserva internamente para checks abiertos.</p><label className="field"><span>Visibilidad al cliente</span><select value={config.tenderDisplayMode} onChange={event=>update("tenderDisplayMode",event.target.value)}><option value="configured">Solo los tenders configurados</option><option value="all">Todos los tenders disponibles del RVC</option></select></label><div className="tender-list">{tenders.map(tender=><label key={tender.tenderId}><input type="checkbox" checked={enabledIds.includes(String(tender.tenderId))} onChange={()=>toggleTender(tender.tenderId)}/><span><b>{tender.name}</b><small>{tender.type} · ID {tender.tenderId}{isCashOrCard(tender)?" · sugerido":""}</small></span></label>)}</div></div></details>}</section>
 <section id="sincronizar" className="admin-card wide"><Title n="4" title="Sincronizar menú" text="Publica catálogo, imágenes y modificadores al e-commerce de esta sesión."/><div className="activate-menu"><span>{locked?"Valida primero la conexión.":"Conexión validada. Sincroniza y publica el menú real con un paso."}</span><button type="button" className="post-button" onClick={()=>void run("activateMenu")} disabled={locked||!config.menuId}>{busy==="activateMenu"?"Sincronizando...":"Sincronizar y activar e-commerce"}</button></div></section>
 <section id="prueba" className="admin-card wide danger"><Title n="5" title="Prueba técnica directa" text="Opcional: crea un check de entrenamiento con un producto validado."/><div className="inline-actions"><Field label="menuItemId" type="number" value={config.menuItemId} onChange={v=>update("menuItemId",v)}/><Field label="Cantidad" type="number" value={config.quantity} onChange={v=>update("quantity",v)}/><button type="button" className="post-button" onClick={()=>void run("trainingCheck")} disabled={locked||!config.menuItemId}>Crear training check</button></div></section></form>
 <section className="result-card"><div><span className="admin-kicker">DETALLE TÉCNICO</span><h2>{message}</h2></div>{result&&<details><summary>Ver respuesta de Simphony</summary><pre>{JSON.stringify(result,null,2)}</pre></details>}</section>
 <section id="logs" className="api-log"><div><span className="admin-kicker">LOG LOCAL DE API</span><h2>Últimas respuestas</h2><p>Solo guarda hora, acción, estado y mensaje. Nunca muestra ni conserva credenciales.</p></div>{!apiLog.length?<p className="empty-log">Aún no hay solicitudes en esta sesión.</p>:<div className="log-list">{apiLog.map((entry,index)=><div className={entry.ok?"log-entry ok":"log-entry error"} key={`${entry.time}-${index}`}><span>{entry.time}</span><b>{entry.action}</b><em>HTTP {entry.status||"—"} · {entry.elapsed} ms</em><small>{entry.message}</small></div>)}</div>}</section></main>;
}
function extractUrl(value:string){return value.match(/https?:\/\/[^\s]+/)?.[0]||value;}
function isCashOrCard(tender:Tender){return /cash|efectivo|card|tarjeta|credit|debit/.test(`${tender.name} ${tender.type}`.toLowerCase());}
function Title({n,title,text}:{n:string;title:string;text:string}){return <div className="card-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>;}
function Field({label,type="text",value,onChange,placeholder,required}:{label:string;type?:string;value:string;onChange:(value:string)=>void;placeholder?:string;required?:boolean}){return <label className="field"><span>{label}{required&&<b> *</b>}</span><input type={type} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} required={required}/></label>;}
