"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import "./simphony-admin.css";

type Config = Record<"apiBaseUrl"|"oidcBaseUrl"|"clientId"|"username"|"password"|"orgShortName"|"locRef"|"rvcRef"|"employeeRef"|"orderTypeRef"|"orderChannelRef"|"menuId"|"menuItemId"|"quantity", string>;
type Action = "test"|"menuSummary"|"menu"|"trainingCheck"|"activateMenu";
const initial:Config = { apiBaseUrl:"", oidcBaseUrl:"", clientId:"", username:"", password:"", orgShortName:"", locRef:"", rvcRef:"", employeeRef:"", orderTypeRef:"", orderChannelRef:"", menuId:"", menuItemId:"", quantity:"1" };

export default function SimphonyAdmin() {
  const [config,setConfig] = useState<Config>(initial); const [result,setResult] = useState<unknown>(null); const [message,setMessage] = useState("Completa la conexion y prueba autenticacion antes de consultar el menu."); const [busy,setBusy] = useState<Action|null>(null);
  const update=(key:keyof Config,value:string)=>setConfig(current=>({...current,[key]:value}));
  async function run(action:Action) { setBusy(action); setResult(null); setMessage("Conectando con Simphony..."); try { const response=await fetch("/api/simphony",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,config})}); const data=await response.json(); if(action==="activateMenu"&&data.ok&&data.sessionId) sessionStorage.setItem("omniorder.simphonySession",data.sessionId); setResult(data); setMessage(data.message || "Operacion completada."); } catch {setMessage("No fue posible comunicarse con el servidor local del lab.");} finally {setBusy(null);} }
  function submit(event:FormEvent){event.preventDefault();void run("test");}
  return <main className="admin-shell"><header className="admin-header"><Link href="/" className="back">← Volver al e-commerce</Link><div><span className="admin-kicker">CONFIGURACION LOCAL</span><h1>Admin de Simphony STS Gen 2</h1></div><span className="local-only">● Solo sesion actual</span></header>
    <section className="admin-intro"><b>Las credenciales no se guardan ni se suben a Git.</b><span>Se conservan solamente en la memoria del servidor local mientras la sesion del catalogo este activa.</span></section>
    <form onSubmit={submit} className="admin-grid"><section className="admin-card"><Title n="1" title="Conexion OIDC" text="Valores de EMC: Services URL y OpenID Provider."/><Field label="STS Gen2 Services URL" value={config.apiBaseUrl} onChange={v=>update("apiBaseUrl",v)} placeholder="https://.../api/v2" required/><Field label="OpenID Provider URL" value={config.oidcBaseUrl} onChange={v=>update("oidcBaseUrl",v)} placeholder="https://.../oidc-provider/v1" required/><Field label="Client ID" value={config.clientId} onChange={v=>update("clientId",v)} required/><Field label="Usuario API" value={config.username} onChange={v=>update("username",v)} required/><Field label="Contrasena API" type="password" value={config.password} onChange={v=>update("password",v)} required/></section>
      <section className="admin-card"><Title n="2" title="Contexto de tu lab" text="Donde Simphony debe crear el training check."/><Field label="orgShortName" value={config.orgShortName} onChange={v=>update("orgShortName",v.toLowerCase())} required/><Field label="locRef" value={config.locRef} onChange={v=>update("locRef",v.toLowerCase())} required/><Field label="rvcRef" type="number" value={config.rvcRef} onChange={v=>update("rvcRef",v)} required/><Field label="checkEmployeeRef" type="number" value={config.employeeRef} onChange={v=>update("employeeRef",v)}/><Field label="orderTypeRef" type="number" value={config.orderTypeRef} onChange={v=>update("orderTypeRef",v)}/><Field label="orderChannelRef" type="number" value={config.orderChannelRef} onChange={v=>update("orderChannelRef",v)}/><button disabled={busy!==null} className="test-button" type="submit">{busy==="test"?"Probando...":"Probar autenticacion y RVC"}</button></section>
      <section className="admin-card wide"><Title n="3" title="Catalogo real para e-commerce" text="El e-commerce recibe nombre, descripcion, precio, imagen y reglas de modificadores expuestas por STS Gen2."/><div className="inline-actions"><button type="button" onClick={()=>void run("menuSummary")} disabled={busy!==null}>1. Ver menus disponibles</button><Field label="menuId" value={config.menuId} onChange={v=>update("menuId",v)} placeholder="Pega el ID del menu"/><button type="button" onClick={()=>void run("menu")} disabled={busy!==null}>2. Revisar catalogo</button></div><div className="inline-actions activate-menu"><span>Si la revision es correcta, activa el catalogo para esta sesion de navegador.</span><button type="button" className="post-button" onClick={()=>void run("activateMenu")} disabled={busy!==null||!config.menuId}>{busy==="activateMenu"?"Activando...":"3. Activar catalogo en e-commerce"}</button></div></section>
      <section className="admin-card wide danger"><Title n="4" title="Prueba tecnica directa" text="Opcional: crea un training check con un ID validado."/><div className="inline-actions"><Field label="menuItemId" type="number" value={config.menuItemId} onChange={v=>update("menuItemId",v)}/><Field label="Cantidad" type="number" value={config.quantity} onChange={v=>update("quantity",v)}/><button type="button" className="post-button" onClick={()=>void run("trainingCheck")} disabled={busy!==null||!config.menuItemId}>Crear training check</button></div></section></form>
    <section className="result-card"><span className="admin-kicker">RESULTADO</span><h2>{message}</h2>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section></main>;
}
function Title({n,title,text}:{n:string;title:string;text:string}){return <div className="card-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>;}
function Field({label,type="text",value,onChange,placeholder,required}:{label:string;type?:string;value:string;onChange:(value:string)=>void;placeholder?:string;required?:boolean}){return <label className="field"><span>{label}{required&&<b> *</b>}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required}/></label>;}
