"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import "./simphony-admin.css";
import "./redwood-status.css";

type Config=Record<"apiBaseUrl"|"oidcBaseUrl"|"clientId"|"username"|"password"|"orgShortName"|"locRef"|"rvcRef"|"employeeRef"|"orderTypeRef"|"orderChannelRef"|"tenderId"|"menuId"|"menuItemId"|"quantity",string>;
type Action="test"|"menuSummary"|"menu"|"trainingCheck"|"activateMenu"|"tenders";
type Status="pending"|"testing"|"connected"|"error";
type ApiLog={time:string;action:string;status:number;ok:boolean;elapsed:number;message:string};
type Tender={tenderId:number;name:string;type:string};
const initial:Config={apiBaseUrl:"",oidcBaseUrl:"",clientId:"",username:"",password:"",orgShortName:"",locRef:"",rvcRef:"",employeeRef:"",orderTypeRef:"",orderChannelRef:"",tenderId:"",menuId:"",menuItemId:"",quantity:"1"};
const CONFIG_KEY="omniorder.adminConfig"; const CONFIG_TTL=60*60*1000;
function loadConfig(){if(typeof window==="undefined")return initial;try{const saved=JSON.parse(sessionStorage.getItem(CONFIG_KEY)||"{}");return saved.expiresAt>Date.now()?saved.config as Config:initial;}catch{return initial;}}

export default function SimphonyAdmin(){
 const [config,setConfig]=useState<Config>(loadConfig);const [status,setStatus]=useState<Status>("pending");const [message,setMessage]=useState("Aun no se ha validado la conexion.");const [result,setResult]=useState<unknown>(null);const [busy,setBusy]=useState<Action|null>(null);const [lastValidated,setLastValidated]=useState<string>();const [elapsed,setElapsed]=useState<number>();const [catalogStatus,setCatalogStatus]=useState("No sincronizado");const [tenders,setTenders]=useState<Tender[]>([]);const [apiLog,setApiLog]=useState<ApiLog[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(sessionStorage.getItem("omniorder.orderLog")||"[]");}catch{return[];}});
 useEffect(()=>{const persist=()=>sessionStorage.setItem(CONFIG_KEY,JSON.stringify({config,expiresAt:Date.now()+CONFIG_TTL}));persist();["click","keydown","pointerdown"].forEach(event=>window.addEventListener(event,persist));return()=>["click","keydown","pointerdown"].forEach(event=>window.removeEventListener(event,persist));},[config]);
 const update=(key:keyof Config,value:string)=>setConfig(current=>({...current,[key]:key==="apiBaseUrl"||key==="oidcBaseUrl"?extractUrl(value):value}));
 async function run(action:Action){const started=performance.now();setBusy(action);setResult(null);if(action==="test"){setStatus("testing");setMessage("Autenticando y validando el Revenue Center...");}else setMessage("Ejecutando operacion con Simphony...");try{const response=await fetch("/api/simphony",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,config})});const data=await response.json();const milliseconds=Math.round(performance.now()-started);setElapsed(milliseconds);setResult(data);setMessage(data.message||"Operacion completada.");setApiLog(current=>[{time:new Date().toLocaleTimeString(),action,status:Number(data.status||response.status),ok:Boolean(data.ok),elapsed:milliseconds,message:String(data.message||"Sin mensaje")},...current].slice(0,12));if(action==="test"){if(data.ok){setStatus("connected");setLastValidated(new Date().toLocaleTimeString());}else setStatus("error");}if(action==="tenders"&&data.ok){const available=(data.tenders||[]) as Tender[];setTenders(available);const recommended=available.find(tender=>tender.type.toLowerCase()==="servicetotal");if(recommended&&!config.tenderId)update("tenderId",String(recommended.tenderId));}if(action==="menuSummary"&&data.ok)setCatalogStatus("Menus recibidos");if(action==="menu"&&data.ok)setCatalogStatus("Catalogo revisado");if(action==="activateMenu"&&data.ok&&data.sessionId){sessionStorage.setItem("omniorder.simphonySession",data.sessionId);setCatalogStatus("Catalogo activo");}if(action!=="test"&&!data.ok)setCatalogStatus("Sincronizacion con error");}catch{const milliseconds=Math.round(performance.now()-started);setMessage("No fue posible comunicarse con el servidor local del lab.");setApiLog(current=>[{time:new Date().toLocaleTimeString(),action,status:0,ok:false,elapsed:milliseconds,message:"Sin respuesta del servidor local"},...current].slice(0,12));if(action==="test")setStatus("error");}finally{setBusy(null);}}
 function submit(event:FormEvent){event.preventDefault();void run("test");}
 const locked=status!=="connected"||busy!==null;
 return <main className="admin-shell"><header className="admin-header"><Link href="/" className="back">← Volver al e-commerce</Link><div><span className="admin-kicker">CONFIGURACION LOCAL</span><h1>Admin de Simphony STS Gen 2</h1></div><span className="local-only">Solo sesion actual</span></header>
 <section className="connection-banner"><div className={`connection-icon ${status}`}>{status==="connected"?"✓":status==="error"?"!":"○"}</div><div><span className="admin-kicker">ESTADO DE CONEXION</span><h2>{status==="connected"?"Conexion validada con Simphony":status==="testing"?"Validando conexion...":status==="error"?"Conexion no validada":"Pendiente de validacion"}</h2><p>{message}</p></div><dl><div><dt>Ultima validacion</dt><dd>{lastValidated||"Sin ejecutar"}</dd></div><div><dt>Tiempo de respuesta</dt><dd>{elapsed!==undefined?`${elapsed} ms`:"—"}</dd></div><div><dt>Catalogo</dt><dd>{status==="connected"?"Listo para sincronizar":"Bloqueado"}</dd></div></dl></section>
 <section className="admin-intro"><b>Las credenciales no se guardan ni se suben a Git.</b><span>Esta pantalla valida autenticacion, acceso al RVC y tiempo de respuesta antes de permitir sincronizar el menu.</span></section>
 <form onSubmit={submit} className="admin-grid"><section className="admin-card"><Title n="1" title="Conexion OIDC" text="Copia los dos valores exactos desde EMC, sin la etiqueta del campo."/><Field label="STS Gen2 Services URL" value={config.apiBaseUrl} onChange={v=>update("apiBaseUrl",v)} placeholder="https://mtu6-sts.oraclecloud.com/api/v1" required/><Field label="OpenID Provider URL" value={config.oidcBaseUrl} onChange={v=>update("oidcBaseUrl",v)} placeholder="https://mtu6-ohra.idm.oracleindustry.com/oidc-provider/" required/><Field label="Client ID" value={config.clientId} onChange={v=>update("clientId",v)} required/><Field label="Usuario API" value={config.username} onChange={v=>update("username",v)} required/><Field label="Contrasena API" type="password" value={config.password} onChange={v=>update("password",v)} required/></section>
 <section className="admin-card"><Title n="2" title="Contexto y menu del lab" text="Destino operativo, tender y menu que se mostrara al cliente."/><Field label="orgShortName" value={config.orgShortName} onChange={v=>update("orgShortName",v.toLowerCase())} required/><Field label="locRef" value={config.locRef} onChange={v=>update("locRef",v.toLowerCase())} required/><Field label="rvcRef" type="number" value={config.rvcRef} onChange={v=>update("rvcRef",v)} required/><Field label="menuId" value={config.menuId} onChange={v=>update("menuId",v)} placeholder="ID del menu que vera el e-commerce" required/><Field label="checkEmployeeRef" type="number" value={config.employeeRef} onChange={v=>update("employeeRef",v)} required/><Field label="orderTypeRef" type="number" value={config.orderTypeRef} onChange={v=>update("orderTypeRef",v)} required/><Field label="orderChannelRef" type="number" value={config.orderChannelRef} onChange={v=>update("orderChannelRef",v)}/><div className="inline-actions"><button type="button" className="test-button" onClick={()=>void run("tenders")} disabled={status!=="connected"||busy!==null}>{busy==="tenders"?"Consultando...":"Consultar tenders del RVC"}</button>{tenders.length>0&&<label className="field"><span>Tender para el demo <b>*</b></span><select value={config.tenderId} onChange={event=>update("tenderId",event.target.value)} required><option value="">Selecciona un tender</option>{tenders.map(tender=><option key={tender.tenderId} value={tender.tenderId}>{tender.name} · {tender.type} · ID {tender.tenderId}{tender.type.toLowerCase()==="servicetotal"?" (recomendado)":""}</option>)}</select></label>}</div>{config.tenderId&&<p className="field"><span>Tender seleccionado: ID {config.tenderId}. Se enviará con total 0 para cubrir el saldo restante.</span></p>}<button disabled={busy!==null} className="test-button" type="submit">{busy==="test"?"Validando...":"Probar autenticacion y RVC"}</button></section>
 <section className="admin-card wide"><Title n="3" title="Sincronizar menu al e-commerce" text="Lee el menu configurado, sus imagenes y modificadores; luego lo deja disponible al cliente en esta sesion."/><div className="activate-menu"><span>{locked?"Valida primero la conexion. Luego se sincronizara el menu indicado arriba.":"Conexion validada. Sincroniza y publica el menu real con un solo paso."}</span><button type="button" className="post-button" onClick={()=>void run("activateMenu")} disabled={locked||!config.menuId}>{busy==="activateMenu"?"Sincronizando...":"Sincronizar y activar e-commerce"}</button></div></section>
 <section className="admin-card wide danger"><Title n="4" title="Prueba tecnica directa" text="Opcional: crea un training check con un ID de producto validado y tender seleccionado."/><div className="inline-actions"><Field label="menuItemId" type="number" value={config.menuItemId} onChange={v=>update("menuItemId",v)}/><Field label="Cantidad" type="number" value={config.quantity} onChange={v=>update("quantity",v)}/><button type="button" className="post-button" onClick={()=>void run("trainingCheck")} disabled={locked||!config.menuItemId||!config.tenderId}>Crear training check</button></div></section></form>
 <section className="result-card"><div><span className="admin-kicker">DETALLE TECNICO</span><h2>{message}</h2></div>{result&&<details><summary>Ver respuesta de Simphony</summary><pre>{JSON.stringify(result,null,2)}</pre></details>}</section><section className="api-log" aria-label="Registro de respuestas API"><div><span className="admin-kicker">LOG LOCAL DE API</span><h2>Últimas respuestas</h2><p>Solo guarda hora, acción, estado y mensaje de esta pantalla. Nunca muestra ni conserva credenciales.</p></div>{!apiLog.length?<p className="empty-log">Aún no hay solicitudes en esta sesión.</p>:<div className="log-list">{apiLog.map((entry,index)=><div className={entry.ok?"log-entry ok":"log-entry error"} key={`${entry.time}-${index}`}><span>{entry.time}</span><b>{entry.action}</b><em>HTTP {entry.status||"—"} · {entry.elapsed} ms</em><small>{entry.message}</small></div>)}</div>}</section></main>;
}
function extractUrl(value:string){return value.match(/https?:\/\/[^\s]+/)?.[0]||value;}
function Title({n,title,text}:{n:string;title:string;text:string}){return <div className="card-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>;}
function Field({label,type="text",value,onChange,placeholder,required}:{label:string;type?:string;value:string;onChange:(value:string)=>void;placeholder?:string;required?:boolean}){return <label className="field"><span>{label}{required&&<b> *</b>}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required}/></label>;}
